---
- include_vars:
    file: "{{ playbook_dir }}/../demos/{{demo}}.yml"

- name: Deploy tower-infra workloads
  include_role:
    name: "{{ tower_infra_vars }}"
  loop: "{{ tower_infra_workloads }}"
  loop_control:
    loop_var: tower_infra_vars
  when:
    - tower_infra_workloads | d("") | length >0